apiVersion: v1
kind: Secret
metadata:
    name: db-secret
type: Opaque
data:
    DB_HOST: ZmFzdGFwaS1kYi5jeXgybXdvNG1lNnIudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
    DB_USER: YWRtaW4=
    DB_PASSWORD: YWRtaW5hd3NyZHNteXNxbA==
    DB_NAME: ZmFzdGFwaV90ZXN0X2Ri